#!/usr/bin/env python3
"""Download the brand's OFL fonts as STATIC instances, with licences and a manifest.

Why static: Chrome renders *variable* fonts into Type3 outlines when it prints to
PDF. Type3 text cannot be selected, searched or reliably reproduced by a print
shop. verify_pdf.py fails any build that contains one.

Why this particular fetch: the Google Fonts CSS API serves a different file per
user agent. A modern browser gets a variable woff2 (and, per weight, tiny
unicode-range subsets); an ancient IE agent gets EOT, which Chrome cannot use.
The Chrome-30 agent below gets the **full static face as WOFF** — one file per
weight and style, which is exactly what a print build needs.

The manifest records the resolved URL, SHA-256, byte count and date for every
file. It is the evidence behind the licence claim — never state that a font is
licensed from memory; read it from here.

Usage:
  fetch_fonts.py                      # into Products/_assets/fonts
  fetch_fonts.py --check              # verify files against the manifest
  fetch_fonts.py --force              # re-download everything
"""
import argparse
import datetime
import hashlib
import json
import os
import re
import subprocess
import sys

# Old enough to be served complete static WOFF, new enough to be served WOFF at all.
FETCH_UA = ("Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36")
CSS_API = "https://fonts.googleapis.com/css2?family="
REPO = "https://raw.githubusercontent.com/google/fonts/main/ofl"
EXT = ".woff"

# local file stem -> (css2 query, css family name, weight, style)
FACES = {
    "Fraunces-Regular":     ("Fraunces:opsz,wght@72,400",         "Fraunces", 400, "normal"),
    "Fraunces-SemiBold":    ("Fraunces:opsz,wght@72,600",         "Fraunces", 600, "normal"),
    "Fraunces-Display":     ("Fraunces:opsz,wght@144,600",        "Fraunces Display", 600, "normal"),
    "Fraunces-Italic":      ("Fraunces:ital,opsz,wght@1,72,400",  "Fraunces", 400, "italic"),
    "SourceSans3-Regular":  ("Source+Sans+3:wght@400",            "Source Sans 3", 400, "normal"),
    "SourceSans3-SemiBold": ("Source+Sans+3:wght@600",            "Source Sans 3", 600, "normal"),
    "SourceSans3-Italic":   ("Source+Sans+3:ital,wght@1,400",     "Source Sans 3", 400, "italic"),
    "IBMPlexMono-Regular":  ("IBM+Plex+Mono:wght@400",            "IBM Plex Mono", 400, "normal"),
    "IBMPlexMono-SemiBold": ("IBM+Plex+Mono:wght@600",            "IBM Plex Mono", 600, "normal"),
}
LICENCES = {"OFL-Fraunces.txt": f"{REPO}/fraunces/OFL.txt",
            "OFL-SourceSans3.txt": f"{REPO}/sourcesans3/OFL.txt",
            "OFL-IBMPlexMono.txt": f"{REPO}/ibmplexmono/OFL.txt"}
FONT_MAGIC = (b"wOFF", b"wOF2", b"\x00\x01\x00\x00", b"true", b"OTTO")


def curl(url, ua=None, binary=True):
    """Python's urllib has no CA bundle on this machine; curl does."""
    cmd = ["curl", "-sSL", "--fail", "--max-time", "60"]
    if ua:
        cmd += ["-H", f"User-Agent: {ua}"]
    cmd.append(url)
    p = subprocess.run(cmd, capture_output=True)
    if p.returncode != 0:
        raise RuntimeError(p.stderr.decode()[:200].strip() or f"curl exit {p.returncode}")
    return p.stdout if binary else p.stdout.decode("utf-8", "replace")


def resolve(query):
    """Ask the CSS API for one face and return the font URL it offers."""
    css = curl(CSS_API + query, ua=FETCH_UA, binary=False)
    urls = re.findall(r"src:\s*url\((https://[^)]+)\)", css)
    if not urls:
        raise RuntimeError("no src url in the CSS response")
    return urls[0]


def fonts_css(manifest, path):
    """Generate the @font-face sheet the products link to."""
    out = ["/* Generated by fetch_fonts.py - do not edit by hand.",
           " * Static instances only: variable fonts become Type3 in Chrome's PDF output.",
           " */", ""]
    for stem, rec in sorted(manifest["fonts"].items()):
        out += ["@font-face {",
                f"  font-family: \"{rec['css_family']}\";",
                f"  font-style: {rec['style']};",
                f"  font-weight: {rec['weight']};",
                f"  src: url(\"{stem}{EXT}\") format(\"woff\");",
                "  font-display: block;",
                "}", ""]
    open(path, "w").write("\n".join(out))


def licence_sheet(manifest, path):
    fams = sorted({r["css_family"].replace(" Display", "") for r in manifest["fonts"].values()})
    sheet = ["# Font licences", "",
             "Every font in this product is licensed under the **SIL Open Font License 1.1**,",
             "which permits commercial use and embedding in PDFs. The font files are never",
             "sold or redistributed on their own. The full licence text sits beside this file.", ""]
    for f in fams:
        dates = [r["date"] for r in manifest["fonts"].values() if r["css_family"].startswith(f)]
        sheet.append(f"- **{f}** - OFL 1.1 - fetched {min(dates)} from Google Fonts")
    sheet += ["", "SHA-256 of every file: `manifest.json`."]
    open(path, "w").write("\n".join(sheet) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="Products/_assets/fonts")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args()

    os.makedirs(a.dir, exist_ok=True)
    mpath = os.path.join(a.dir, "manifest.json")
    manifest = json.load(open(mpath)) if os.path.exists(mpath) else {}
    manifest.setdefault("fonts", {})
    manifest.setdefault("licences", {})

    fails, got = [], []

    if a.check:
        for stem in FACES:
            rec = manifest["fonts"].get(stem)
            dest = os.path.join(a.dir, stem + EXT)
            if not rec:
                fails.append(f"{stem}: missing from the manifest")
            elif not os.path.exists(dest):
                fails.append(f"{stem}{EXT}: file missing")
            elif hashlib.sha256(open(dest, "rb").read()).hexdigest() != rec["sha256"]:
                fails.append(f"{stem}{EXT}: sha256 changed - licence evidence broken")
        for name in LICENCES:
            if not os.path.exists(os.path.join(a.dir, name)):
                fails.append(f"{name}: licence text missing")
        if not os.path.exists(os.path.join(a.dir, "fonts.css")):
            fails.append("fonts.css: missing - products have nothing to link")
    else:
        for stem, (query, family, weight, style) in FACES.items():
            dest = os.path.join(a.dir, stem + EXT)
            if os.path.exists(dest) and stem in manifest["fonts"] and not a.force:
                print(f"  have  {stem}{EXT}")
                continue
            try:
                url = resolve(query)
                data = curl(url)
                if not data.startswith(FONT_MAGIC):
                    raise RuntimeError(f"not a font file (starts {data[:4]!r})")
            except Exception as e:                      # noqa: BLE001
                fails.append(f"{stem}: {e}")
                continue
            open(dest, "wb").write(data)
            manifest["fonts"][stem] = {
                "css_family": family, "weight": weight, "style": style,
                "query": query, "url": url, "container": data[:4].decode("latin1"),
                "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data),
                "date": datetime.date.today().isoformat(),
                "licence": "SIL Open Font License 1.1",
            }
            got.append(stem)
            print(f"  got   {stem}{EXT}  ({len(data):,} bytes)")

        for name, url in LICENCES.items():
            dest = os.path.join(a.dir, name)
            if os.path.exists(dest) and name in manifest["licences"] and not a.force:
                continue
            if os.path.exists(dest) and not a.force:
                # Already on disk from an earlier run: record it rather than
                # re-downloading, so the manifest is complete either way.
                data = open(dest, "rb").read()
                manifest["licences"][name] = {
                    "url": url, "sha256": hashlib.sha256(data).hexdigest(),
                    "date": datetime.date.fromtimestamp(os.path.getmtime(dest)).isoformat()}
                print(f"  kept  {name}")
                continue
            try:
                data = curl(url)
            except Exception as e:                      # noqa: BLE001
                fails.append(f"{name}: {e}")
                continue
            open(dest, "wb").write(data)
            manifest["licences"][name] = {
                "url": url, "sha256": hashlib.sha256(data).hexdigest(),
                "date": datetime.date.today().isoformat()}
            print(f"  got   {name}")

        if manifest["fonts"]:
            json.dump(manifest, open(mpath, "w"), indent=2, sort_keys=True)
            fonts_css(manifest, os.path.join(a.dir, "fonts.css"))
            licence_sheet(manifest, os.path.join(a.dir, "FONT-LICENCES.md"))

    if fails:
        print("\nFAIL", file=sys.stderr)
        for f in fails:
            print("  " + f, file=sys.stderr)
        return 1
    print(f"\nOK - {len(manifest['fonts'])} faces, {len(manifest['licences'])} licences in {a.dir}"
          + (f"; {len(got)} newly fetched" if got else ""))
    if got:
        print("     fonts.css and FONT-LICENCES.md regenerated.")
        print("     Now prove it: render a page and check verify_pdf.py reports no Type3 font.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
